/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MomentsRouteImport } from './routes/moments'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminCirclesRouteImport } from './routes/admin.circles'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminKittyRouteImport } from './routes/admin.kitty'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as MembersCalendarRouteImport } from './routes/members.calendar'
import { Route as MembersCircleRouteImport } from './routes/members.circle'
import { Route as MembersKittyRouteImport } from './routes/members.kitty'
import { Route as MembersPeopleRouteImport } from './routes/members.people'
import { Route as AdminApplicationsIndexRouteImport } from './routes/admin.applications.index'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications.$id'
import { Route as AdminCirclesIndexRouteImport } from './routes/admin.circles.index'
import { Route as AdminCirclesIdRouteImport } from './routes/admin.circles.$id'
import { Route as AdminCirclesNewRouteImport } from './routes/admin.circles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MomentsRoute = MomentsRouteImport.update({
  id: '/moments',
  path: '/moments',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCirclesRoute = AdminCirclesRouteImport.update({
  id: '/admin/circles',
  path: '/admin/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKittyRoute = AdminKittyRouteImport.update({
  id: '/admin/kitty',
  path: '/admin/kitty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/admin/notices',
  path: '/admin/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersCalendarRoute = MembersCalendarRouteImport.update({
  id: '/members/calendar',
  path: '/members/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersCircleRoute = MembersCircleRouteImport.update({
  id: '/members/circle',
  path: '/members/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersKittyRoute = MembersKittyRouteImport.update({
  id: '/members/kitty',
  path: '/members/kitty',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersPeopleRoute = MembersPeopleRouteImport.update({
  id: '/members/people',
  path: '/members/people',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsIndexRoute = AdminApplicationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminApplicationsRoute,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminApplicationsRoute,
} as any)
const AdminCirclesIndexRoute = AdminCirclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCirclesRoute,
} as any)
const AdminCirclesIdRoute = AdminCirclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCirclesRoute,
} as any)
const AdminCirclesNewRoute = AdminCirclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCirclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/circle': typeof CircleRoute
  '/login': typeof LoginRoute
  '/moments': typeof MomentsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/circles': typeof AdminCirclesRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/kitty': typeof AdminKittyRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/members/calendar': typeof MembersCalendarRoute
  '/members/circle': typeof MembersCircleRoute
  '/members/kitty': typeof MembersKittyRoute
  '/members/people': typeof MembersPeopleRoute
  '/admin/': typeof AdminIndexRoute
  '/members/': typeof MembersIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/circles/$id': typeof AdminCirclesIdRoute
  '/admin/circles/new': typeof AdminCirclesNewRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/circles/': typeof AdminCirclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/circle': typeof CircleRoute
  '/login': typeof LoginRoute
  '/moments': typeof MomentsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/kitty': typeof AdminKittyRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/members/calendar': typeof MembersCalendarRoute
  '/members/circle': typeof MembersCircleRoute
  '/members/kitty': typeof MembersKittyRoute
  '/members/people': typeof MembersPeopleRoute
  '/admin': typeof AdminIndexRoute
  '/members': typeof MembersIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/circles/$id': typeof AdminCirclesIdRoute
  '/admin/circles/new': typeof AdminCirclesNewRoute
  '/admin/applications': typeof AdminApplicationsIndexRoute
  '/admin/circles': typeof AdminCirclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apply': typeof ApplyRoute
  '/circle': typeof CircleRoute
  '/login': typeof LoginRoute
  '/moments': typeof MomentsRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRouteWithChildren
  '/admin/circles': typeof AdminCirclesRouteWithChildren
  '/admin/events': typeof AdminEventsRoute
  '/admin/kitty': typeof AdminKittyRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/members/calendar': typeof MembersCalendarRoute
  '/members/circle': typeof MembersCircleRoute
  '/members/kitty': typeof MembersKittyRoute
  '/members/people': typeof MembersPeopleRoute
  '/admin/': typeof AdminIndexRoute
  '/members/': typeof MembersIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/circles/$id': typeof AdminCirclesIdRoute
  '/admin/circles/new': typeof AdminCirclesNewRoute
  '/admin/applications/': typeof AdminApplicationsIndexRoute
  '/admin/circles/': typeof AdminCirclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apply'
    | '/circle'
    | '/login'
    | '/moments'
    | '/privacy'
    | '/terms'
    | '/admin/applications'
    | '/admin/circles'
    | '/admin/events'
    | '/admin/kitty'
    | '/admin/members'
    | '/admin/notices'
    | '/members/calendar'
    | '/members/circle'
    | '/members/kitty'
    | '/members/people'
    | '/admin/'
    | '/members/'
    | '/admin/applications/$id'
    | '/admin/circles/$id'
    | '/admin/circles/new'
    | '/admin/applications/'
    | '/admin/circles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apply'
    | '/circle'
    | '/login'
    | '/moments'
    | '/privacy'
    | '/terms'
    | '/admin/events'
    | '/admin/kitty'
    | '/admin/members'
    | '/admin/notices'
    | '/members/calendar'
    | '/members/circle'
    | '/members/kitty'
    | '/members/people'
    | '/admin'
    | '/members'
    | '/admin/applications/$id'
    | '/admin/circles/$id'
    | '/admin/circles/new'
    | '/admin/applications'
    | '/admin/circles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apply'
    | '/circle'
    | '/login'
    | '/moments'
    | '/privacy'
    | '/terms'
    | '/admin/applications'
    | '/admin/circles'
    | '/admin/events'
    | '/admin/kitty'
    | '/admin/members'
    | '/admin/notices'
    | '/members/calendar'
    | '/members/circle'
    | '/members/kitty'
    | '/members/people'
    | '/admin/'
    | '/members/'
    | '/admin/applications/$id'
    | '/admin/circles/$id'
    | '/admin/circles/new'
    | '/admin/applications/'
    | '/admin/circles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ApplyRoute: typeof ApplyRoute
  CircleRoute: typeof CircleRoute
  LoginRoute: typeof LoginRoute
  MomentsRoute: typeof MomentsRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRouteWithChildren
  AdminCirclesRoute: typeof AdminCirclesRouteWithChildren
  AdminEventsRoute: typeof AdminEventsRoute
  AdminKittyRoute: typeof AdminKittyRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  MembersCalendarRoute: typeof MembersCalendarRoute
  MembersCircleRoute: typeof MembersCircleRoute
  MembersKittyRoute: typeof MembersKittyRoute
  MembersPeopleRoute: typeof MembersPeopleRoute
  AdminIndexRoute: typeof AdminIndexRoute
  MembersIndexRoute: typeof MembersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moments': {
      id: '/moments'
      path: '/moments'
      fullPath: '/moments'
      preLoaderRoute: typeof MomentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/circles': {
      id: '/admin/circles'
      path: '/admin/circles'
      fullPath: '/admin/circles'
      preLoaderRoute: typeof AdminCirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kitty': {
      id: '/admin/kitty'
      path: '/admin/kitty'
      fullPath: '/admin/kitty'
      preLoaderRoute: typeof AdminKittyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/admin/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/calendar': {
      id: '/members/calendar'
      path: '/members/calendar'
      fullPath: '/members/calendar'
      preLoaderRoute: typeof MembersCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/circle': {
      id: '/members/circle'
      path: '/members/circle'
      fullPath: '/members/circle'
      preLoaderRoute: typeof MembersCircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/kitty': {
      id: '/members/kitty'
      path: '/members/kitty'
      fullPath: '/members/kitty'
      preLoaderRoute: typeof MembersKittyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/people': {
      id: '/members/people'
      path: '/members/people'
      fullPath: '/members/people'
      preLoaderRoute: typeof MembersPeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications/': {
      id: '/admin/applications/'
      path: '/'
      fullPath: '/admin/applications/'
      preLoaderRoute: typeof AdminApplicationsIndexRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/admin/applications/$id': {
      id: '/admin/applications/$id'
      path: '/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminApplicationsRoute
    }
    '/admin/circles/': {
      id: '/admin/circles/'
      path: '/'
      fullPath: '/admin/circles/'
      preLoaderRoute: typeof AdminCirclesIndexRouteImport
      parentRoute: typeof AdminCirclesRoute
    }
    '/admin/circles/$id': {
      id: '/admin/circles/$id'
      path: '/$id'
      fullPath: '/admin/circles/$id'
      preLoaderRoute: typeof AdminCirclesIdRouteImport
      parentRoute: typeof AdminCirclesRoute
    }
    '/admin/circles/new': {
      id: '/admin/circles/new'
      path: '/new'
      fullPath: '/admin/circles/new'
      preLoaderRoute: typeof AdminCirclesNewRouteImport
      parentRoute: typeof AdminCirclesRoute
    }
  }
}

interface AdminApplicationsRouteChildren {
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminApplicationsIndexRoute: typeof AdminApplicationsIndexRoute
}

const AdminApplicationsRouteChildren: AdminApplicationsRouteChildren = {
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminApplicationsIndexRoute: AdminApplicationsIndexRoute,
}

const AdminApplicationsRouteWithChildren =
  AdminApplicationsRoute._addFileChildren(AdminApplicationsRouteChildren)

interface AdminCirclesRouteChildren {
  AdminCirclesIdRoute: typeof AdminCirclesIdRoute
  AdminCirclesNewRoute: typeof AdminCirclesNewRoute
  AdminCirclesIndexRoute: typeof AdminCirclesIndexRoute
}

const AdminCirclesRouteChildren: AdminCirclesRouteChildren = {
  AdminCirclesIdRoute: AdminCirclesIdRoute,
  AdminCirclesNewRoute: AdminCirclesNewRoute,
  AdminCirclesIndexRoute: AdminCirclesIndexRoute,
}

const AdminCirclesRouteWithChildren = AdminCirclesRoute._addFileChildren(
  AdminCirclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ApplyRoute: ApplyRoute,
  CircleRoute: CircleRoute,
  LoginRoute: LoginRoute,
  MomentsRoute: MomentsRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminApplicationsRoute: AdminApplicationsRouteWithChildren,
  AdminCirclesRoute: AdminCirclesRouteWithChildren,
  AdminEventsRoute: AdminEventsRoute,
  AdminKittyRoute: AdminKittyRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  MembersCalendarRoute: MembersCalendarRoute,
  MembersCircleRoute: MembersCircleRoute,
  MembersKittyRoute: MembersKittyRoute,
  MembersPeopleRoute: MembersPeopleRoute,
  AdminIndexRoute: AdminIndexRoute,
  MembersIndexRoute: MembersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
